In [1]:
import pandas as pd

books = pd.read_csv("books_cleaned.csv")

In [2]:
books["categories"].value_counts().reset_index()

                          categories  count
0                            Fiction    517
1                   Juvenile Fiction    154
2          Biography & Autobiography     81
3                            History     49
4                Juvenile Nonfiction     26
..                               ...    ...
125           Bosnia and Hercegovina      1
126                           Bibles      1
127                   Christian life      1
128         Fantasy fiction, English      1
129  People with social disabilities      1

[130 rows x 2 columns]

In [3]:
books["categories"].value_counts().reset_index().query("count > 50")

                  categories  count
0                    Fiction    517
1           Juvenile Fiction    154
2  Biography & Autobiography     81

In [4]:
books[books["categories"] == "Juvenile Fiction"]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
11,9780030547744,0030547741,Where the Red Fern Grows,Wilson Rawls,Juvenile Fiction,http://books.google.com/books/content?id=IHpRw...,A young boy living in the Ozarks achieves his ...,2000.0,4.37,288.0,95.0,Where the Red Fern Grows: The Story of Two Dog...,9780030547744 A young boy living in the Ozarks...
12,9780060004507,0060004509,An Old-Fashioned Thanksgiving,Louisa May Alcott;James Bernardin,Juvenile Fiction,http://books.google.com/books/content?id=SKYr4...,An adaptation of the original story follows th...,2005.0,3.70,32.0,599.0,An Old-Fashioned Thanksgiving,9780060004507 An adaptation of the original st...
13,9780060099459,0060099453,"Merry Christmas, Amelia Bedelia",Peggy Parish,Juvenile Fiction,http://books.google.com/books/content?id=SYCUL...,"It's Christmas Eve, and Amelia Bedelia has to ...",2002.0,4.29,64.0,2452.0,"Merry Christmas, Amelia Bedelia","9780060099459 It's Christmas Eve, and Amelia B..."
15,9780060541880,0060541881,Johnny and the Dead,Terry Pratchett,Juvenile Fiction,http://books.google.com/books/content?id=HgU8r...,After twelve-year-old Johnny Maxwell suddenly ...,2006.0,3.78,213.0,7733.0,Johnny and the Dead,9780060541880 After twelve-year-old Johnny Max...
16,9780060543495,0060543493,The Girls of Lighthouse Lane #3,Thomas Kinkade;Erika Tamar,Juvenile Fiction,http://books.google.com/books/content?id=2LXIP...,"During a scarlet fever outbreak in 1906, thirt...",2005.0,3.96,192.0,24.0,The Girls of Lighthouse Lane #3: Lizabeth's Story,9780060543495 During a scarlet fever outbreak ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1165,9781590171240,1590171241,An Episode of Sparrows,Rumer Godden,Juvenile Fiction,http://books.google.com/books/content?id=wLgdp...,"In post-World War II London, two street-tough ...",2004.0,4.20,247.0,851.0,An Episode of Sparrows: A Novel,"9781590171240 In post-World War II London, two..."
1169,9781590385814,1590385810,Fablehaven,Brandon Mull,Juvenile Fiction,http://books.google.com/books/content?id=tbVIP...,When Kendra and Seth go to stay at their grand...,2006.0,4.09,351.0,111896.0,Fablehaven,9781590385814 When Kendra and Seth go to stay ...
1192,9781596792500,1596792507,Sherlock Holmes and the Case of the Hound of t...,Arthur Conan Doyle;Malvina G. Vogel,Juvenile Fiction,http://books.google.com/books/content?id=EWgWP...,Sherlock Holmes and Dr. Watson travel to the b...,2005.0,4.51,237.0,28.0,Sherlock Holmes and the Case of the Hound of t...,9781596792500 Sherlock Holmes and Dr. Watson t...
1196,9781599900056,159990005X,The Drift House,Dale Peck,Juvenile Fiction,http://books.google.com/books/content?id=kbwPY...,Sent to stay with their uncle in a ship-like h...,2006.0,3.64,437.0,595.0,The Drift House: The First Voyage,9781599900056 Sent to stay with their uncle in...
1221,9781932416374,1932416374,The Very Persistent Gappers of Frip,George Saunders;Lane Smith,Juvenile Fiction,http://books.google.com/books/content?id=xYJOP...,A novel set in the seaside village of Frip fol...,2006.0,4.11,84.0,2317.0,The Very Persistent Gappers of Frip,9781932416374 A novel set in the seaside villa...

In [5]:
books[books["categories"] == "Juvenile Nonfiction"]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
114,9780142302279,0142302279,Dirty Beasts,Roald Dahl,Juvenile Nonfiction,NaN,Poems tell the stories of a smart pig who outw...,2002.0,4.02,32.0,3953.0,Dirty Beasts,9780142302279 Poems tell the stories of a smar...
119,9780142407929,0142407925,The BFG,Roald Dahl;David Wood;Jane Walmsley,Juvenile Nonfiction,http://books.google.com/books/content?id=aDf-O...,"With notes on staging, props, and costumes, a ...",2007.0,4.26,128.0,452.0,The BFG: A Set of Plays,"9780142407929 With notes on staging, props, an..."
174,9780198320272,0198320272,Julius Caesar,William Shakespeare,Juvenile Nonfiction,http://books.google.com/books/content?id=Nlmkh...,Caesar returns from a triumphant battle to Rom...,2001.0,3.67,128.0,133575.0,Julius Caesar,9780198320272 Caesar returns from a triumphant...
334,9780375823787,0375823786,Ancient Greece and the Olympics,Mary Pope Osborne;Natalie Pope Boyce,Juvenile Nonfiction,http://books.google.com/books/content?id=5cPbW...,"Filled with fascinating facts, a Magic Tree Ho...",2004.0,4.06,119.0,1044.0,Ancient Greece and the Olympics: A Nonfiction ...,"9780375823787 Filled with fascinating facts, a..."
458,9780439420068,0439420067,Eat!,Roberta Grobel Intrater,Juvenile Nonfiction,http://books.google.com/books/content?id=BnQ2n...,A group of babies enjoys some favorite foods--...,2002.0,3.95,10.0,54.0,Eat!,9780439420068 A group of babies enjoys some fa...
466,9780439736466,0439736463,"Where We Are, what We See",David Levithan,Juvenile Nonfiction,NaN,"A collection of poems, stories, essays, and ar...",2005.0,3.73,288.0,41.0,"Where We Are, what We See: The Best Young Arti...","9780439736466 A collection of poems, stories, ..."
486,9780440229353,0440229359,How Angel Peterson Got His Name,Gary Paulsen,Juvenile Nonfiction,http://books.google.com/books/content?id=maJrL...,Author Gary Paulsen relates tales from his you...,2004.0,3.93,111.0,1139.0,How Angel Peterson Got His Name: And Other Out...,9780440229353 Author Gary Paulsen relates tale...
528,9780448437439,0448437430,Who Was John F. Kennedy?,Yona Zeldis McDonough;Jill Weber,Juvenile Nonfiction,http://books.google.com/books/content?id=qjCzJ...,Chronicles the life of the president who saw A...,2004.0,4.19,112.0,598.0,Who Was John F. Kennedy?,9780448437439 Chronicles the life of the presi...
530,9780448444826,0448444828,Who Was Anne Frank?,Ann Abramson,Juvenile Nonfiction,http://books.google.com/books/content?id=Bz37n...,Looks closely at Anne Frank's life before the ...,2007.0,4.26,103.0,1763.0,Who Was Anne Frank?,9780448444826 Looks closely at Anne Frank's li...
590,9780486276809,0486276805,The Secret Garden Coloring Book,Frances Hodgson Burnett,Juvenile Nonfiction,http://books.google.com/books/content?id=sxHdA...,Ten-year-old Mary comes to live in a lonely ho...,2014.0,4.25,48.0,4.0,The Secret Garden Coloring Book,9780486276809 Ten-year-old Mary comes to live ...
632,9780525469780,0525469788,"Boy, Were We Wrong about Dinosaurs!",Kathleen V. Kudlinski,Juvenile Nonfiction,http://books.google.com/books/content?id=QrRKD...,"Examines what is known about dinosaur bones, b...",2005.0,3.93,32.0,243.0,"Boy, Were We Wrong about Dinosaurs!",9780525469780 Examines what is known about din...
696,9780590032490,0590032496,The witches,Roald Dahl,Juvenile Nonfiction,http://books.google.com/books/content?id=tpQxo...,"A young boy and his Norwegian grandmother, who...",1997.0,4.17,208.0,254867.0,The witches,9780590032490 A young boy and his Norwegian gr...
809,9780689834196,0689834195,Salt in His Shoes,Deloris Jordan;Roslyn M. Jordan,Juvenile Nonfiction,http://books.google.com/books/content?id=hYzQw...,"Young Michael Jordan, who is smaller than the ...",2003.0,4.21,32.0,1054.0,Salt in His Shoes: Michael Jordan in Pursuit o...,"9780689834196 Young Michael Jordan, who is sma..."
816,9780689869907,0689869908,Beatrice's Goat,Page McBrier,Juvenile Nonfiction,http://books.google.com/books/content?id=4MNED...,In this story based on a case from Project Hei...,2004.0,4.24,40.0,523.0,Beatrice's Goat,9780689869907 In this story based on a case fr...
818,9780689876707,068987670X,Star Bright,Cathy Hapka,Juvenile Nonfiction,http://books.google.com/books/content?id=JPuiC...,PopTV is going to follow Star around for twent...,2005.0,3.67,160.0,3.0,Star Bright,9780689876707 PopTV is going to follow Star ar...
826,9780736805995,0736805990,"The Girlhood Diary of Louisa May Alcott, 1843-...",Louisa May Alcott,Juvenile Nonfiction,http://books.google.com/books/content?id=_dP35...,Excerpts from the girlhood diary of Louisa May...,2001.0,3.87,32.0,26.0,"The Girlhood Diary of Louisa May Alcott, 1843-...",9780736805995 Excerpts from the girlhood diary...
833,9780739844328,0739844326,Bill Gates,Sara Barton-Wood,Juvenile Nonfiction,http://books.google.com/books/content?id=Fr814...,"Presents the life of Bill Gates, from his chil...",2001.0,5.00,48.0,0.0,Bill Gates: Computer Legend,"9780739844328 Presents the life of Bill Gates,..."
875,9780756614195,0756614198,Star Wars,Kristin Lund;Simon Beecroft;Kerrie Dougherty,Juvenile Nonfiction,http://books.google.com/books/content?id=PAq2A...,Glorious full-color illustrations create a sea...,2005.0,4.30,175.0,128.0,Star Wars: Complete Locations,9780756614195 Glorious full-color illustration...
924,9780791070482,0791070484,Bram Stoker's Dracula,Harold Bloom,Juvenile Nonfiction,http://books.google.com/books/content?id=vQ6SQ...,Presents a collection of critical essays on Br...,2003.0,3.83,243.0,6.0,Bram Stoker's Dracula,9780791070482 Presents a collection of critica...
925,9780791081266,0791081265,Edith Wharton's The Age of Innocence,Harold Bloom,Juvenile Nonfiction,http://books.google.com/books/content?id=MNuFk...,One of Edith Wharton's most critically acclaim...,2005.0,3.71,205.0,11.0,Edith Wharton's The Age of Innocence,9780791081266 One of Edith Wharton's most crit...
942,9780805069853,0805069852,You Come Too,Robert Frost,Juvenile Nonfiction,http://books.google.com/books/content?id=gZWM6...,An introduction to Robert Frost features an ab...,2002.0,4.16,92.0,77.0,You Come Too: Favorite Poems for Readers of Al...,9780805069853 An introduction to Robert Frost ...
955,9780810935204,0810935201,Lewis Carroll's Jabberwocky,Graeme Base,Juvenile Nonfiction,http://books.google.com/books/content?id=tyMFA...,Lewis Carroll's classic and inventive verse co...,1996.0,4.14,14.0,31.0,Lewis Carroll's Jabberwocky: A Book of Brillig...,9780810935204 Lewis Carroll's classic and inve...
988,9780823410781,0823410781,A Picture Book of Anne Frank,NaN,Juvenile Nonfiction,http://books.google.com/books/content?id=CSNxW...,Traces the life of the young Jewish girl whose...,1993.0,4.17,32.0,208.0,A Picture Book of Anne Frank,9780823410781 Traces the life of the young Jew...
1085,9781400307845,1400307848,Writings to Young Women from Laura Ingalls Wil...,Laura Ingalls Wilder;Stephen W. Hines,Juvenile Nonfiction,http://books.google.com/books/content?id=e5gSD...,Using selections from her works and memoirs of...,2006.0,3.95,113.0,100.0,Writings to Young Women from Laura Ingalls Wil...,9781400307845 Using selections from her works ...
1116,9781560067849,1560067845,Flowers for Algernon,Patrice Cassedy,Juvenile Nonfiction,http://books.google.com/books/content?id=x_CUf...,"Discusses the young adult book ""Flowers for Al...",2000.0,3.00,96.0,1.0,Flowers for Algernon,"9781560067849 Discusses the young adult book ""..."
1219,9781931414166,1931414165,The Brooklyn Bridge,Elizabeth Mann;Alan Witschonke,Juvenile Nonfiction,http://books.google.com/books/content?id=s28MA...,Describes the construction of the Brooklyn Bri...,2006.0,4.44,46.0,35.0,The Brooklyn Bridge,9781931414166 Describes the construction of th...

In [6]:
category_mapping = {'Fiction' : "Fiction",
 'Juvenile Fiction': "Children's Fiction",
 'Biography & Autobiography': "Nonfiction",
 'History': "Nonfiction",
 'Literary Criticism': "Nonfiction",
 'Philosophy': "Nonfiction",
 'Religion': "Nonfiction",
 'Comics & Graphic Novels': "Fiction",
 'Drama': "Fiction",
 'Juvenile Nonfiction': "Children's Nonfiction",
 'Science': "Nonfiction",
 'Poetry': "Fiction"}

books["simple_categories"] = books["categories"].map(category_mapping)

In [7]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_categories
0,9780006472612,0006472613,Master of the Game,Sidney Sheldon,Adventure stories,http://books.google.com/books/content?id=TkTYp...,Kate Blackwell is an enigma and one of the mos...,1982.0,4.11,489.0,43540.0,Master of the Game,9780006472612 Kate Blackwell is an enigma and ...,NaN
1,9780006483892,0006483895,Murder in LaMut,Raymond E. Feist;Joel Rosenberg,Adventure stories,http://books.google.com/books/content?id=I2jbB...,"Available in the U.S. for the first time, this...",2003.0,3.70,337.0,5083.0,Murder in LaMut,9780006483892 Available in the U.S. for the fi...,NaN
2,9780006496892,000649689X,Glittering Images,Susan Howatch,English fiction,http://books.google.com/books/content?id=rDHbn...,"It is 1937, and Charles Ashworth, a Canon to t...",1996.0,4.07,512.0,2045.0,Glittering Images,"9780006496892 It is 1937, and Charles Ashworth...",NaN
3,9780006496922,000649692X,Glamorous Powers,Susan Howatch,Clergy,http://books.google.com/books/content?id=_bhPY...,Reissue of the author's most famous and well-l...,1996.0,4.20,512.0,1441.0,Glamorous Powers,9780006496922 Reissue of the author's most fam...,NaN
4,9780007120680,0007120680,Hallowe'en Party,Agatha Christie,"Poirot, Hercule (Fictitious character)",http://books.google.com/books/content?id=Qlx98...,No one believes a little girl when she insists...,2001.0,3.66,336.0,18820.0,Hallowe'en Party,9780007120680 No one believes a little girl wh...,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1224,9781932664393,1932664394,Han'guk-sik Sarang,J. Torres,Comics & Graphic Novels,http://books.google.com/books/content?id=V1Fex...,"Joel, an English teacher, has never really lik...",2006.0,3.44,58.0,9.0,Han'guk-sik Sarang,"9781932664393 Joel, an English teacher, has ne...",Fiction
1225,9781932857085,1932857087,Real Rule of Four,Joscelyn Godwin,History,http://books.google.com/books/content?id=X2-fi...,Discusses the historical and intellectual back...,2004.0,3.45,208.0,88.0,Real Rule of Four: The Unauthorized Guide to t...,9781932857085 Discusses the historical and int...,Nonfiction
1226,9781933615097,1933615095,The Best of America's Test Kitchen 2007,America's Test Kitchen,Cooking,http://books.google.com/books/content?id=tQ97A...,Presents nearly one thousand recipes--from app...,2006.0,4.34,312.0,185.0,The Best of America's Test Kitchen 2007: The Y...,9781933615097 Presents nearly one thousand rec...,NaN
1227,9781933771137,1933771135,Neptune Noir,Rob Thomas;Leah Wilson,Performing Arts,http://books.google.com/books/content?id=VHu3w...,Edited by the creator and executive producer o...,2007.0,3.64,224.0,911.0,Neptune Noir: Unauthorized Investigations Into...,9781933771137 Edited by the creator and execut...,NaN
1228,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,134.0,"Cry, the Peacock",9788122200850 This book is the story of a youn...,Fiction

In [8]:
books[~(books["simple_categories"].isna())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_categories
10,9780029221303,0029221307,The Origins of the Civil Rights Movement,Aldon D. Morris,History,http://books.google.com/books/content?id=7vyHY...,A blending of scholarly research and interview...,1986.0,4.04,368.0,145.0,The Origins of the Civil Rights Movement,9780029221303 A blending of scholarly research...,Nonfiction
11,9780030547744,0030547741,Where the Red Fern Grows,Wilson Rawls,Juvenile Fiction,http://books.google.com/books/content?id=IHpRw...,A young boy living in the Ozarks achieves his ...,2000.0,4.37,288.0,95.0,Where the Red Fern Grows: The Story of Two Dog...,9780030547744 A young boy living in the Ozarks...,Children's Fiction
12,9780060004507,0060004509,An Old-Fashioned Thanksgiving,Louisa May Alcott;James Bernardin,Juvenile Fiction,http://books.google.com/books/content?id=SKYr4...,An adaptation of the original story follows th...,2005.0,3.70,32.0,599.0,An Old-Fashioned Thanksgiving,9780060004507 An adaptation of the original st...,Children's Fiction
13,9780060099459,0060099453,"Merry Christmas, Amelia Bedelia",Peggy Parish,Juvenile Fiction,http://books.google.com/books/content?id=SYCUL...,"It's Christmas Eve, and Amelia Bedelia has to ...",2002.0,4.29,64.0,2452.0,"Merry Christmas, Amelia Bedelia","9780060099459 It's Christmas Eve, and Amelia B...",Children's Fiction
14,9780060177249,0060177241,The thief of always,Clive Barker,Fiction,http://books.google.com/books/content?id=jKsrA...,After a mysterious stranger promises to end hi...,1992.0,4.19,225.0,22123.0,The thief of always: a fable,9780060177249 After a mysterious stranger prom...,Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1222,9781932416480,193241648X,McSweeney's,T. C. Boyle,Fiction,http://books.google.com/books/content?id=N5nFA...,The latest collection from the literary journa...,2006.0,3.80,250.0,303.0,McSweeney's,9781932416480 The latest collection from the l...,Fiction
1223,9781932420302,1932420304,Erotica,Kelly Carr,Fiction,http://books.google.com/books/content?id=5TS3A...,"""My Dirty Thirties"" takes female empowerment t...",2004.0,2.44,152.0,6.0,Erotica: My Dirty Thirties: Male/Female/Male,"9781932420302 ""My Dirty Thirties"" takes female...",Fiction
1224,9781932664393,1932664394,Han'guk-sik Sarang,J. Torres,Comics & Graphic Novels,http://books.google.com/books/content?id=V1Fex...,"Joel, an English teacher, has never really lik...",2006.0,3.44,58.0,9.0,Han'guk-sik Sarang,"9781932664393 Joel, an English teacher, has ne...",Fiction
1225,9781932857085,1932857087,Real Rule of Four,Joscelyn Godwin,History,http://books.google.com/books/content?id=X2-fi...,Discusses the historical and intellectual back...,2004.0,3.45,208.0,88.0,Real Rule of Four: The Unauthorized Guide to t...,9781932857085 Discusses the historical and int...,Nonfiction
1228,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,134.0,"Cry, the Peacock",9788122200850 This book is the story of a youn...,Fiction

In [9]:
import torch  # Make sure this is the first import
from transformers import pipeline

fiction_categories = ["Fiction", "Nonfiction"]

# Force CPU by using device=-1
pipe = pipeline(
    "zero-shot-classification",
    model="facebook/bart-large-mnli",
    device=-1  # CPU
)

Device set to use cpu

In [10]:
sequence = books.loc[books["simple_categories"] == "Fiction", "description"].reset_index(drop=True)[0]

In [11]:
pipe(sequence, fiction_categories)

{'sequence': 'After a mysterious stranger promises to end his boredom with a trip to the magical Holiday House, ten-year-old Harvey learns that his fun has a high price',
 'labels': ['Fiction', 'Nonfiction'],
 'scores': [0.6067743301391602, 0.39322561025619507]}

In [12]:
import numpy as np

max_index = np.argmax(pipe(sequence, fiction_categories)["scores"])
max_label = pipe(sequence, fiction_categories)["labels"][max_index]
max_label

'Fiction'

In [13]:
def generate_predictions(sequence, categories):
    predictions = pipe(sequence, categories)
    max_index = np.argmax(predictions["scores"])
    max_label = predictions["labels"][max_index]
    return max_label

In [14]:
from tqdm import tqdm

actual_cats = []
predicted_cats = []

for i in tqdm(range(0, 300)):
    sequence = books.loc[books["simple_categories"] == "Fiction", "description"].reset_index(drop=True)[i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    actual_cats += ["Fiction"]

100%|██████████| 300/300 [04:01<00:00,  1.24it/s]

In [17]:
nonfiction_books = books.loc[books["simple_categories"] == "Nonfiction", "description"].reset_index(drop=True)
for sequence in tqdm(nonfiction_books):
    predicted_cats.append(generate_predictions(sequence, fiction_categories))
    actual_cats.append("Nonfiction")

100%|██████████| 208/208 [03:15<00:00,  1.06it/s]

In [18]:
predictions_df = pd.DataFrame({"actual_categories": actual_cats, "predicted_categories": predicted_cats})

In [19]:
predictions_df

    actual_categories predicted_categories
0             Fiction              Fiction
1             Fiction              Fiction
2             Fiction              Fiction
3             Fiction              Fiction
4             Fiction           Nonfiction
..                ...                  ...
711        Nonfiction           Nonfiction
712        Nonfiction           Nonfiction
713        Nonfiction           Nonfiction
714        Nonfiction           Nonfiction
715        Nonfiction              Fiction

[716 rows x 2 columns]

In [21]:
predictions_df["correct_prediction"] = (
    np.where(predictions_df["actual_categories"] == predictions_df["predicted_categories"], 1, 0)
)

In [22]:
predictions_df["correct_prediction"].sum() / len(predictions_df)

0.7723463687150838

In [24]:
isbns = []
predicted_cats = []

missing_cats = books.loc[books["simple_categories"].isna(), ["isbn13", "description"]].reset_index(drop=True)

In [25]:
for i in tqdm(range(0, len(missing_cats))):
    sequence = missing_cats["description"][i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    isbns += [missing_cats["isbn13"][i]]

100%|██████████| 270/270 [04:15<00:00,  1.06it/s]

In [26]:
missing_predicted_df = pd.DataFrame({"isbn13": isbns, "predicted_categories": predicted_cats})

In [27]:
missing_predicted_df

            isbn13 predicted_categories
0    9780006472612           Nonfiction
1    9780006483892              Fiction
2    9780006496892           Nonfiction
3    9780006496922              Fiction
4    9780007120680              Fiction
..             ...                  ...
265  9781859848982           Nonfiction
266  9781880685358           Nonfiction
267  9781929229482           Nonfiction
268  9781933615097           Nonfiction
269  9781933771137           Nonfiction

[270 rows x 2 columns]

In [28]:
books = pd.merge(books, missing_predicted_df, on="isbn13", how="left")
books["simple_categories"] = np.where(books["simple_categories"].isna(), books["predicted_categories"], books["simple_categories"])
books = books.drop(columns = ["predicted_categories"])

In [29]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_categories
0,9780006472612,0006472613,Master of the Game,Sidney Sheldon,Adventure stories,http://books.google.com/books/content?id=TkTYp...,Kate Blackwell is an enigma and one of the mos...,1982.0,4.11,489.0,43540.0,Master of the Game,9780006472612 Kate Blackwell is an enigma and ...,Nonfiction
1,9780006483892,0006483895,Murder in LaMut,Raymond E. Feist;Joel Rosenberg,Adventure stories,http://books.google.com/books/content?id=I2jbB...,"Available in the U.S. for the first time, this...",2003.0,3.70,337.0,5083.0,Murder in LaMut,9780006483892 Available in the U.S. for the fi...,Fiction
2,9780006496892,000649689X,Glittering Images,Susan Howatch,English fiction,http://books.google.com/books/content?id=rDHbn...,"It is 1937, and Charles Ashworth, a Canon to t...",1996.0,4.07,512.0,2045.0,Glittering Images,"9780006496892 It is 1937, and Charles Ashworth...",Nonfiction
3,9780006496922,000649692X,Glamorous Powers,Susan Howatch,Clergy,http://books.google.com/books/content?id=_bhPY...,Reissue of the author's most famous and well-l...,1996.0,4.20,512.0,1441.0,Glamorous Powers,9780006496922 Reissue of the author's most fam...,Fiction
4,9780007120680,0007120680,Hallowe'en Party,Agatha Christie,"Poirot, Hercule (Fictitious character)",http://books.google.com/books/content?id=Qlx98...,No one believes a little girl when she insists...,2001.0,3.66,336.0,18820.0,Hallowe'en Party,9780007120680 No one believes a little girl wh...,Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1224,9781932664393,1932664394,Han'guk-sik Sarang,J. Torres,Comics & Graphic Novels,http://books.google.com/books/content?id=V1Fex...,"Joel, an English teacher, has never really lik...",2006.0,3.44,58.0,9.0,Han'guk-sik Sarang,"9781932664393 Joel, an English teacher, has ne...",Fiction
1225,9781932857085,1932857087,Real Rule of Four,Joscelyn Godwin,History,http://books.google.com/books/content?id=X2-fi...,Discusses the historical and intellectual back...,2004.0,3.45,208.0,88.0,Real Rule of Four: The Unauthorized Guide to t...,9781932857085 Discusses the historical and int...,Nonfiction
1226,9781933615097,1933615095,The Best of America's Test Kitchen 2007,America's Test Kitchen,Cooking,http://books.google.com/books/content?id=tQ97A...,Presents nearly one thousand recipes--from app...,2006.0,4.34,312.0,185.0,The Best of America's Test Kitchen 2007: The Y...,9781933615097 Presents nearly one thousand rec...,Nonfiction
1227,9781933771137,1933771135,Neptune Noir,Rob Thomas;Leah Wilson,Performing Arts,http://books.google.com/books/content?id=VHu3w...,Edited by the creator and executive producer o...,2007.0,3.64,224.0,911.0,Neptune Noir: Unauthorized Investigations Into...,9781933771137 Edited by the creator and execut...,Nonfiction
1228,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,134.0,"Cry, the Peacock",9788122200850 This book is the story of a youn...,Fiction

In [31]:
books[books["categories"].str.lower().isin([
    "romance",
    "science fiction",
    "scifi",
    "fantasy",
    "horror",
    "mystery",
    "thriller",
    "comedy",
    "crime",
    "historical"
])]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description,simple_categories
191,9780261102422,0261102427,The Silmarillion,John Ronald Reuel Tolkien,Fantasy,http://books.google.com/books/content?id=22ePu...,Tolkien's Silmarillion is the core work of the...,1999.0,3.91,384.0,253.0,The Silmarillion,9780261102422 Tolkien's Silmarillion is the co...,Fiction
266,9780345251220,0345251229,Visions from Nowhere,William Arrow,Science fiction,NaN,"The first novel in the series, ""Return to the ...",1976.0,3.23,183.0,10.0,Visions from Nowhere,"9780345251220 The first novel in the series, ""...",Fiction
878,9780760728505,076072850X,"20,000 Leagues Under the Sea",Jules Verne,Science fiction,NaN,Retells the adventures of a French professor a...,2002.0,3.88,394.0,135778.0,"20,000 Leagues Under the Sea",9780760728505 Retells the adventures of a Fren...,Fiction

In [32]:
books.to_csv("books_with_categories.csv", index=False)