In [1]:
from langchain_community.document_loaders.text import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma

In [2]:
from dotenv import load_dotenv

load_dotenv()

False

In [3]:
import pandas as pd

books = pd.read_csv("books_cleaned.csv")

In [4]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
0,9780006472612,0006472613,Master of the Game,Sidney Sheldon,Adventure stories,http://books.google.com/books/content?id=TkTYp...,Kate Blackwell is an enigma and one of the mos...,1982.0,4.11,489.0,43540.0,Master of the Game,9780006472612 Kate Blackwell is an enigma and ...
1,9780006483892,0006483895,Murder in LaMut,Raymond E. Feist;Joel Rosenberg,Adventure stories,http://books.google.com/books/content?id=I2jbB...,"Available in the U.S. for the first time, this...",2003.0,3.70,337.0,5083.0,Murder in LaMut,9780006483892 Available in the U.S. for the fi...
2,9780006496892,000649689X,Glittering Images,Susan Howatch,English fiction,http://books.google.com/books/content?id=rDHbn...,"It is 1937, and Charles Ashworth, a Canon to t...",1996.0,4.07,512.0,2045.0,Glittering Images,"9780006496892 It is 1937, and Charles Ashworth..."
3,9780006496922,000649692X,Glamorous Powers,Susan Howatch,Clergy,http://books.google.com/books/content?id=_bhPY...,Reissue of the author's most famous and well-l...,1996.0,4.20,512.0,1441.0,Glamorous Powers,9780006496922 Reissue of the author's most fam...
4,9780007120680,0007120680,Hallowe'en Party,Agatha Christie,"Poirot, Hercule (Fictitious character)",http://books.google.com/books/content?id=Qlx98...,No one believes a little girl when she insists...,2001.0,3.66,336.0,18820.0,Hallowe'en Party,9780007120680 No one believes a little girl wh...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1224,9781932664393,1932664394,Han'guk-sik Sarang,J. Torres,Comics & Graphic Novels,http://books.google.com/books/content?id=V1Fex...,"Joel, an English teacher, has never really lik...",2006.0,3.44,58.0,9.0,Han'guk-sik Sarang,"9781932664393 Joel, an English teacher, has ne..."
1225,9781932857085,1932857087,Real Rule of Four,Joscelyn Godwin,History,http://books.google.com/books/content?id=X2-fi...,Discusses the historical and intellectual back...,2004.0,3.45,208.0,88.0,Real Rule of Four: The Unauthorized Guide to t...,9781932857085 Discusses the historical and int...
1226,9781933615097,1933615095,The Best of America's Test Kitchen 2007,America's Test Kitchen,Cooking,http://books.google.com/books/content?id=tQ97A...,Presents nearly one thousand recipes--from app...,2006.0,4.34,312.0,185.0,The Best of America's Test Kitchen 2007: The Y...,9781933615097 Presents nearly one thousand rec...
1227,9781933771137,1933771135,Neptune Noir,Rob Thomas;Leah Wilson,Performing Arts,http://books.google.com/books/content?id=VHu3w...,Edited by the creator and executive producer o...,2007.0,3.64,224.0,911.0,Neptune Noir: Unauthorized Investigations Into...,9781933771137 Edited by the creator and execut...
1228,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,134.0,"Cry, the Peacock",9788122200850 This book is the story of a youn...

In [5]:
books["tagged_description"]

0       9780006472612 Kate Blackwell is an enigma and ...
1       9780006483892 Available in the U.S. for the fi...
2       9780006496892 It is 1937, and Charles Ashworth...
3       9780006496922 Reissue of the author's most fam...
4       9780007120680 No one believes a little girl wh...
                              ...
1224    9781932664393 Joel, an English teacher, has ne...
1225    9781932857085 Discusses the historical and int...
1226    9781933615097 Presents nearly one thousand rec...
1227    9781933771137 Edited by the creator and execut...
1228    9788122200850 This book is the story of a youn...
Name: tagged_description, Length: 1229, dtype: object

In [6]:
books["tagged_description"].to_csv("tagged_description.txt",
                                   sep = "\n",
                                   index = False,
                                   header = False)

In [7]:
raw_documents = TextLoader("tagged_description.txt").load()
text_splitter = CharacterTextSplitter(chunk_size=500, chunk_overlap=50, separator="\n")
documents = text_splitter.split_documents(raw_documents)

In [8]:
documents[0]

Document(metadata={'source': 'tagged_description.txt'}, page_content='9780006472612 Kate Blackwell is an enigma and one of the most powerful women in the world. But at her ninetieth birthday celebrations there are ghosts of absent friends and absent enemies.\n"9780006483892 Available in the U.S. for the first time, this is the second volume in the exceptional Legends of the Riftwar series from ""New York Times""-bestselling authors Feist and Rosenberg."')

In [9]:
embedding_model = HuggingFaceEmbeddings(
    model_name="all-MiniLM-L6-v2"  # lightweight, fast model
)

# Build the Chroma vectorstore
db_books = Chroma.from_documents(
    documents,
    embedding=embedding_model
)

C:\Users\abhin\PycharmProjects\book-recommender\.venv\Lib\site-packages\huggingface_hub\file_download.py:945: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [10]:
query = "A book to teach children about nature"
docs = db_books.similarity_search(query, k = 10)
docs

[Document(id='d01484bc-cd58-4d18-9719-2ce7603feef7', metadata={'source': 'tagged_description.txt'}, page_content='9788122200850 This book is the story of a young girl obsessed by a childhood prophecy of disaster. The author builds up an atmosphere of tension and oppression, in the middle of an Indian summer.'),
 Document(id='ddbe855d-e177-4948-a373-2d5b3e7a364f', metadata={'source': 'tagged_description.txt'}, page_content="9780689862465 Whistler and Lila, two of the mice children who live in a lighthouse, meet a young octopus when they visit the beach during low tide.\n9780689869907 In this story based on a case from Project Heifer, a young girl's dream of attending school in her small Ugandan village is fulfilled after her family is given an income-producing goat."),
 Document(id='e424e27c-9977-464e-9edc-6b251b7663ca', metadata={'source': 'tagged_description.txt'}, page_content="9780240806082 Michael Rabiger guides the reader through the stages required to conceive, edit and produce a documentary. He also provides advice on the law, ethics and authorship as well as career possibilities and finding work.\n9780241003008 Eric Carle's children's classic is the story of a very small and very hungry caterpillar who manages to nibble his way through the pages of this enchanting book."),
 Document(id='8c0fe364-5d1b-4d14-80fa-cf7f139b3b92', metadata={'source': 'tagged_description.txt'}, page_content='9781589971288 In addition to advice on topics such as sibling conflict and lying, Whelchel offers this handy reference guide that provides a biblical perspective and down to-earth encouragement to parents who are feeling overwhelmed.\n9781590171240 In post-World War II London, two street-tough children attempt to build a hidden garden, an act that awakens hidden courage in the children and profoundly disrupts the neighborhood.'),
 Document(id='efbd8eb4-3779-4b33-90c1-79cfbb26f7d8', metadata={'source': 'tagged_description.txt'}, page_content='9780679420255 Ten different and thoroughly dissimilar novels intertwine as the beginning of each book, interrupted at a critical moment of suspense, leads into yet another novel reflecting yet another literary mode\n9780679451211 A guide for bird enthusiasts specifically designed for use in the field features descriptions of 703 species of birds from west of the Rocky Mountains, and illustrations that depict species from different views.'),
 Document(id='4c5f852b-fda8-42c8-9d22-72de2340f376', metadata={'source': 'tagged_description.txt'}, page_content="9780007151240 It should be the most natural thing in the world. But in Tony Parsons' latest bestseller, three couples discover that Mother Nature can be one hell of a bitch.\n9780007158522 From bang-ups and hang-ups to lurches and slumps. Dr. Seuss takes a hilarious look at the mishaps and misadventures that life may have in store for us."),
 Document(id='585a14f3-8d1f-40b1-b020-61690b085a3b', metadata={'source': 'tagged_description.txt'}, page_content="9780393311037 A collection of essays answers questions about key scientific concepts, focusing, in particular, on Darwin's theory of evolution, natural selection, and its impact on biology, natural history, and modern science\n9780393315110 Essays by revisionist historians, scientists, and cultural critics explore the connection between nature and American culture, analyzing how it is packaged and presented at places such as Sea World and the Nature Company stores"),
 Document(id='20835d0a-d539-4cff-903a-d1ac7e053980', metadata={'source': 'tagged_description.txt'}, page_content="9780064409902 After grasshoppers ruin the crops, eight-year-old Laura Ingalls and her family leave Plum Creek and move to Burr Oak, Iowa, where they experience life in a small town and help manage a hotel. Reprint.\n9780064410724 The students' scheme to find a love match for their beloved teacher on Valentine's Day turns into a comedy of errors when four stupid cupids from Ancient Greece try to help."),
 Document(id='81860c88-b056-4cf2-81b7-88bfdbea8a2f', metadata={'source': 'tagged_description.txt'}, page_content="9780618391103 Includes four posters depicting Tolkien's world of Middle-Earth with maps from The Hobbit, Beleriand, and Numenor, accompanied by a manual describing the signicance of geographical evolution in the author's works.\n9780618477906 On Christmas eve, a young boy joins some other children on a magical train ride to the North Pole, in an adaptation of the new movie being released this holiday season. Original."),
 Document(id='c2b88149-5550-49af-994a-d932c6e2e617', metadata={'source': 'tagged_description.txt'}, page_content="9780689860072 Menolly flees her home, because she is not permitted to make music there, and is taken by the Masterharper himself to Harpershall, where she learns that only her own self-doubt stands in her way.\n9780689861130 Children will love joining in and imitating the animal noises and sounds in this big, bold board book format, illustrated with Sandra Boynton's seriously silly signature animals.")]

In [11]:
books[books["isbn13"] == int(docs[0].page_content.split()[0].strip())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
1228,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,134.0,"Cry, the Peacock",9788122200850 This book is the story of a youn...

In [12]:
def retrieve_semantic_recommendations(
        query: str,
        top_k: int = 10,
) -> pd.DataFrame:
    recs = db_books.similarity_search(query, k = 50)

    books_list = []

    for i in range(0, len(recs)):
        books_list += [int(recs[i].page_content.strip('"').split()[0])]

    return books[books["isbn13"].isin(books_list)]

In [13]:
retrieve_semantic_recommendations("A book to teach children about nature")

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,title_and_subtitle,tagged_description
6,9780007151240,0007151241,The Family Way,Tony Parsons,Parenthood,http://books.google.com/books/content?id=dJEIx...,It should be the most natural thing in the wor...,2005.0,3.51,400.0,2095.0,The Family Way,9780007151240 It should be the most natural th...
36,9780060976118,006097611X,Operation Wandering Soul,Richard Powers,Fiction,http://books.google.com/books/content?id=nIGIm...,"Highly imaginative and emotionally powerful, t...",1994.0,3.62,352.0,366.0,Operation Wandering Soul,9780060976118 Highly imaginative and emotional...
44,9780064409902,0064409902,Old Town in the Green Groves,Cynthia Rylant;Jim LaMarche,Juvenile Fiction,http://books.google.com/books/content?id=YUQMA...,"After grasshoppers ruin the crops, eight-year-...",2004.0,4.04,176.0,4631.0,Old Town in the Green Groves: Laura Ingalls Wi...,9780064409902 After grasshoppers ruin the crop...
56,9780140110876,0140110879,You Bright and Risen Angels,William T. Vollmann,Fiction,http://books.google.com/books/content?id=d0buA...,This comic and surreal novel about the beastli...,1988.0,4.08,635.0,747.0,You Bright and Risen Angels: A Cartoon,9780140110876 This comic and surreal novel abo...
86,9780140448009,0140448004,Three Tales,Gustave Flaubert;Roger Whitehouse;Geoffrey Wall,Fiction,http://books.google.com/books/content?id=XFzga...,Features short fiction by the French naturalis...,2005.0,3.71,110.0,3050.0,Three Tales,9780140448009 Features short fiction by the Fr...
88,9780140449143,0140449140,The Republic,Plato;Sir Henry Desmond Pritchard Lee,Philosophy,http://books.google.com/books/content?id=R9Paw...,A model for the ideal state includes discussio...,2003.0,3.93,416.0,127393.0,The Republic,9780140449143 A model for the ideal state incl...
90,9780140568196,0140568190,The Giraffe and the Pelly and Me,Roald Dahl;Quentin Blake,Candy,http://books.google.com/books/content?id=J7FdI...,"A Dahl story in which the giraffe, the pelican...",2001.0,3.81,32.0,16265.0,The Giraffe and the Pelly and Me,9780140568196 A Dahl story in which the giraff...
100,9780141186078,0141186070,The Log from the Sea of Cortez,John Steinbeck,Biography & Autobiography,http://books.google.com/books/content?id=9CrIf...,This light-hearted journal tells of John Stein...,2001.0,3.84,288.0,3226.0,The Log from the Sea of Cortez,9780141186078 This light-hearted journal tells...
110,9780142003343,0142003344,The Blank Slate,Steven Pinker,Psychology,http://books.google.com/books/content?id=7rJ5g...,In a study of the nature versus nurture debate...,2003.0,4.08,528.0,17851.0,The Blank Slate: The Modern Denial of Human Na...,9780142003343 In a study of the nature versus ...
116,9780142402498,0142402494,Pippi Longstocking,Astrid Lindgren,Juvenile Fiction,http://books.google.com/books/content?id=STE5P...,Relates the antics of a rambunctious girl who ...,2005.0,4.12,160.0,140107.0,Pippi Longstocking,9780142402498 Relates the antics of a rambunct...
140,9780152057640,0152057641,Beauty Shop for Rent,Laura Bowers,Juvenile Fiction,http://books.google.com/books/content?id=MwoYv...,Raised by a great-grandmother and a bunch of b...,2007.0,3.87,336.0,758.0,"Beauty Shop for Rent: --fully Equipped, Inquir...",9780152057640 Raised by a great-grandmother an...
185,9780240806082,0240806085,Directing the Documentary,Michael Rabiger,Performing Arts,http://books.google.com/books/content?id=uoKli...,Michael Rabiger guides the reader through the ...,2004.0,4.23,648.0,173.0,Directing the Documentary,9780240806082 Michael Rabiger guides the reade...
187,9780241912720,0241912725,Stuart Little,Elwyn Brooks White,"Little, Stuart (Fictitious character)",NaN,The adventures of the debonair mouse Stuart Li...,1946.0,3.89,144.0,109.0,Stuart Little,9780241912720 The adventures of the debonair m...
241,9780312878603,0312878605,The Collected Stories of Arthur C. Clarke,Arthur C. Clarke,Fiction,http://books.google.com/books/content?id=HLz1g...,Introduces readers to the author's shorter wor...,2002.0,4.30,966.0,3964.0,The Collected Stories of Arthur C. Clarke,9780312878603 Introduces readers to the author...
311,9780374528539,0374528535,"Get Out of My Life, But First Could You Drive ...",Anthony E. Wolf,Family & Relationships,http://books.google.com/books/content?id=oKdbC...,A lighthearted but insightful guide to raising...,2002.0,3.94,240.0,1301.0,"Get Out of My Life, But First Could You Drive ...",9780374528539 A lighthearted but insightful gu...
349,9780385302319,0385302312,Dragonfly in Amber,Diana Gabaldon,Fiction,http://books.google.com/books/content?id=zQ4Jy...,"Twenty years after her voyage to Scotland, Cla...",1992.0,4.32,743.0,1018.0,Dragonfly in Amber,9780385302319 Twenty years after her voyage to...
387,9780393311037,0393311031,Hen's Teeth and Horse's Toes,Stephen Jay Gould,Nature,http://books.google.com/books/content?id=EPh9j...,A collection of essays answers questions about...,1994.0,4.10,416.0,1680.0,Hen's Teeth and Horse's Toes,9780393311037 A collection of essays answers q...
413,9780394832203,0394832205,Juniper,Monica Furlong,Occult fiction,http://books.google.com/books/content?id=GpjhJ...,"While apprenticed to the witch woman Juniper, ...",1991.0,4.16,198.0,111.0,Juniper,9780394832203 While apprenticed to the witch w...
457,9780439411370,0439411378,The Summit,Gordon Korman,Juvenile Fiction,http://books.google.com/books/content?id=6VlnC...,"As Tilt, Perry, Sammi, and Dominic prepare to ...",2002.0,3.96,154.0,2515.0,The Summit,"9780439411370 As Tilt, Perry, Sammi, and Domin..."
492,9780440362050,0440362059,My Name is Aram,William Saroyan,Fiction,http://books.google.com/books/content?id=2P3XA...,A small boy finds excitement and promise in th...,1966.0,4.15,151.0,975.0,My Name is Aram,9780440362050 A small boy finds excitement and...
525,9780446677493,0446677493,Hope is the Thing with Feathers,Christopher Cokinos,Nature,http://books.google.com/books/content?id=y7Rmu...,Presents the histories of six extinct North Am...,2001.0,4.21,384.0,294.0,Hope is the Thing with Feathers: A Personal Ch...,9780446677493 Presents the histories of six ex...
557,9780451461636,0451461630,Thin Air,Rachel Caine,Fiction,http://books.google.com/books/content?id=kzuPo...,After Weather Warden Joanne Baldwin prevents M...,2007.0,3.96,307.0,5824.0,Thin Air,9780451461636 After Weather Warden Joanne Bald...
563,9780451528308,0451528301,Ten Great Works of Philosophy,Robert Paul Wolff,Fiction,http://books.google.com/books/content?id=uMxnF...,"From ancient Greece to 19th-century America, t...",2002.0,3.82,592.0,85.0,Ten Great Works of Philosophy,9780451528308 From ancient Greece to 19th-cent...
567,9780451530370,0451530373,"Chekhov, the Major Plays",Anton Pavlovich Chekhov,Drama,http://books.google.com/books/content?id=RvdPA...,This volume includes the classic plays Ivanov ...,2006.0,4.18,406.0,94.0,"Chekhov, the Major Plays",9780451530370 This volume includes the classic...
589,9780486264738,0486264734,Bartleby and Benito Cereno,Herman Melville,Fiction,http://books.google.com/books/content?id=L-shD...,"Two classics in one volume: ""Bartleby,"" a dist...",1990.0,3.80,112.0,2107.0,Bartleby and Benito Cereno,"9780486264738 Two classics in one volume: ""Bar..."
641,9780553213430,0553213431,The Complete Plays of Aristophanes,Aristophanes,Drama,http://books.google.com/books/content?id=j_dvD...,Background information and brief introductions...,1981.0,4.21,577.0,1954.0,The Complete Plays of Aristophanes,9780553213430 Background information and brief...
687,9780553802023,055380202X,The Universe in a Nutshell,Stephen W. Hawking;STEPHEN W AUTOR HAWKING,Science,http://books.google.com/books/content?id=VXIc3...,The author explores recent scientific breakthr...,2001.0,4.15,216.0,27792.0,The Universe in a Nutshell,9780553802023 The author explores recent scien...
711,9780618056736,0618056734,Unweaving the Rainbow,Richard Dawkins,Science,http://books.google.com/books/content?id=GWj0q...,"Offers an assessment of what science is, how i...",2000.0,4.02,352.0,9168.0,"Unweaving the Rainbow: Science, Delusion and t...",9780618056736 Offers an assessment of what sci...
722,9780618391103,061839110X,The Maps of Tolkien's Middle-earth,Brian Sibley,Fiction,http://books.google.com/books/content?id=gCENA...,Includes four posters depicting Tolkien's worl...,2003.0,4.13,80.0,7585.0,The Maps of Tolkien's Middle-earth,9780618391103 Includes four posters depicting ...
726,9780618619160,061861916X,The Ancestor's Tale,Richard Dawkins;Yan Wong,Science,http://books.google.com/books/content?id=rR9XP...,A renowned biologist provides a sweeping chron...,2005.0,4.13,688.0,18593.0,The Ancestor's Tale: A Pilgrimage to the Dawn ...,9780618619160 A renowned biologist provides a ...
758,9780679420255,0679420258,If on a Winter's Night a Traveler,Italo Calvino;William Weaver,Fiction,http://books.google.com/books/content?id=jJSZP...,Ten different and thoroughly dissimilar novels...,1993.0,4.06,254.0,1412.0,If on a Winter's Night a Traveler,9780679420255 Ten different and thoroughly dis...
789,9780679838869,0679838864,Junie B. Jones and a Little Monkey Business,Barbara Park,Juvenile Fiction,http://books.google.com/books/content?id=LRK1m...,"Through a misunderstanding, Junie B. thinks th...",1993.0,3.98,68.0,10723.0,Junie B. Jones and a Little Monkey Business,"9780679838869 Through a misunderstanding, Juni..."
807,9780689716041,0689716044,The Bears on Hemlock Mountain,Alice Dalgliesh,Juvenile Fiction,http://books.google.com/books/content?id=2gt4h...,An eight-year-old boy who is frightened of tra...,1992.0,3.78,64.0,2017.0,The Bears on Hemlock Mountain,9780689716041 An eight-year-old boy who is fri...
813,9780689860072,0689860072,Dragonsinger,Anne McCaffrey,Juvenile Fiction,http://books.google.com/books/content?id=IiLlZ...,"Menolly flees her home, because she is not per...",2003.0,4.28,288.0,34207.0,Dragonsinger,"9780689860072 Menolly flees her home, because ..."
815,9780689862465,0689862466,The Octopus,Cynthia Rylant;Preston McDaniels,Juvenile Fiction,http://books.google.com/books/content?id=8B8-C...,"Whistler and Lila, two of the mice children wh...",2005.0,4.16,64.0,117.0,The Octopus,"9780689862465 Whistler and Lila, two of the mi..."
861,9780744578263,0744578264,The Sea-thing Child,Russell Hoban,Birds,http://books.google.com/books/content?id=CEt9O...,"Washed up on the beach during a storm, the sea...",2000.0,3.79,48.0,100.0,The Sea-thing Child,9780744578263 Washed up on the beach during a ...
864,9780747553861,0747553866,Pastoralia,George Saunders,"Humorous stories, English",http://books.google.com/books/content?id=Y72kA...,Pastoralia was published to huge literary accl...,2001.0,4.11,188.0,12763.0,Pastoralia,9780747553861 Pastoralia was published to huge...
884,9780763619312,0763619310,Judy Moody Gets Famous!,Megan McDonald;Peter Reynolds,Juvenile Fiction,http://books.google.com/books/content?id=11tdd...,When a third grade classmate gets her picture ...,2003.0,4.03,144.0,8080.0,Judy Moody Gets Famous!,9780763619312 When a third grade classmate get...
954,9780809166589,0809166585,Love You Until...,Lisa McCourt,Religion,http://books.google.com/books/content?id=ftwAE...,Mama and Mike take turns saying that they will...,1999.0,4.67,32.0,3.0,Love You Until...,9780809166589 Mama and Mike take turns saying ...
964,9780812501940,0812501942,The Last Castle,Jack Vance;Robert Silverberg,Fiction,NaN,Features Jack Vance's novel of humanity's fina...,1989.0,3.71,182.0,42.0,The Last Castle,9780812501940 Features Jack Vance's novel of h...
978,9780812968378,0812968379,Funny in Farsi,Firoozeh Dumas,Biography & Autobiography,http://books.google.com/books/content?id=PNh9-...,An autobiography of growing up as an Iranian-A...,2004.0,3.79,240.0,12072.0,Funny in Farsi: A Memoir of Growing Up Iranian...,9780812968378 An autobiography of growing up a...
1044,9780933121263,0933121261,Black Man of the Nile and His Family,Yosef Ben-Jochannan,History,http://books.google.com/books/content?id=6EK3B...,"In a masterful and unique manner, Dr. Ben uses...",1989.0,4.56,442.0,175.0,Black Man of the Nile and His Family,9780933121263 In a masterful and unique manner...
1104,9781414306346,1414306342,Looking for God in Harry Potter,John Granger,Literary Criticism,http://books.google.com/books/content?id=2GZlm...,Provides a Christian interpretation of the fir...,2006.0,4.13,234.0,1321.0,Looking for God in Harry Potter,9781414306346 Provides a Christian interpretat...
1108,9781416939214,1416939210,Z for Zachariah,Robert C. O'Brien,Juvenile Fiction,http://books.google.com/books/content?id=w5Gse...,Believing herself to be the only survivor of a...,2007.0,3.65,250.0,1005.0,Z for Zachariah,9781416939214 Believing herself to be the only...
1116,9781560067849,1560067845,Flowers for Algernon,Patrice Cassedy,Juvenile Nonfiction,http://books.google.com/books/content?id=x_CUf...,"Discusses the young adult book ""Flowers for Al...",2000.0,3.00,96.0,1.0,Flowers for Algernon,"9781560067849 Discusses the young adult book ""..."
1150,9781584850557,1584850558,Teacher's Pet,Laurie Halse Anderson,Juvenile Fiction,http://books.google.com/books/content?id=2sjrA...,Adjusting to middle school becomes easier for ...,2001.0,4.07,128.0,170.0,Teacher's Pet,9781584850557 Adjusting to middle school becom...
1162,9781587420245,1587420244,On the Lines of Morris' Romances,William Morris;Michale W. Perry,Fiction,http://books.google.com/books/content?id=LusAA...,J. R. R. Tolkien said that his writing was ins...,2003.0,4.09,288.0,11.0,On the Lines of Morris' Romances: Two Books th...,9781587420245 J. R. R. Tolkien said that his w...
1164,9781589971288,1589971280,Creative Correction,Lisa Whelchel,Family & Relationships,http://books.google.com/books/content?id=haewm...,In addition to advice on topics such as siblin...,2005.0,3.93,367.0,1071.0,Creative Correction: Extraordinary Ideas for E...,9781589971288 In addition to advice on topics ...
1196,9781599900056,159990005X,The Drift House,Dale Peck,Juvenile Fiction,http://books.google.com/books/content?id=kbwPY...,Sent to stay with their uncle in a ship-like h...,2006.0,3.64,437.0,595.0,The Drift House: The First Voyage,9781599900056 Sent to stay with their uncle in...
1228,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,134.0,"Cry, the Peacock",9788122200850 This book is the story of a youn...